module.exports = {
    'ORIENTATIONS': {
        'PORTRAIT': 'PORTRAIT',
        'LANDSCAPE': 'LANDSCAPE',
        'UIA_DEVICE_ORIENTATION_LANDSCAPERIGHT': 'UIA_DEVICE_ORIENTATION_LANDSCAPERIGHT',
        'UIA_DEVICE_ORIENTATION_PORTRAIT_UPSIDEDOWN': 'UIA_DEVICE_ORIENTATION_PORTRAIT_UPSIDEDOWN'
    }
};